version: 2.0.2
name: FireworkShow
authors: [iGufGuf, Jackietkfrost, Zuwel]
main: com.igufguf.fireworkshow.FireworkShow
api-version: 1.16
commands:
  fireworkshow:
    description: Basic Fireworkshow command
    aliases: fws