version: 1.0.2
name: FireworkShow
author: [iGufGuf, Jackietkfrost, Zuwel]
main: com.igufguf.fireworkshow.Main
api-version: 1.14
commands:
  fireworkshow:
    description: Basic Fireworkshow command
    aliases: fws